# Generated by Django 5.0 on 2024-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
