# Generated by Django 5.0 on 2024-01-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
    ]
